version: "3"

services:
  online_store:
    build: .
    image: online_store:a1
    container_name: online_store
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8065
    volumes:
      - "./myshop/:/myshop/"
    ports:
      - 8065:8065
    env_file:
      - env.container

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_myshop
      - POSTGRES_USER=axkxd
      - POSTGRES_PASSWORD=123qweASD
    ports:
      - 5432:5432
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  celery_worker:
    build: .
    image: online_store:celery
    container_name: celery_worker
    restart: on-failure
    command: celery -A myshop worker --loglevel=info
    volumes:
      - "./myshop/:/myshop/"
    env_file:
      - env.container
      
  # flower:
  #   build: .
  #   image: online_store:flower
  #   container_name: flower
  #   restart: always
  #   command: celery -A myshop flower
  #   ports:
  #     - 5555:5555

volumes:
  postgresql_data: